// frontend/food-delivery/src/views/customers/CustomerCart.jsx
import React from "react";
import { useSelector, useDispatch } from "react-redux";
import { removeFromCart, updateQuantity } from "../../redux/CartSlice";
import Order from '../../models/Order'
import { useUserContext } from "../../contexts/UserProvider";

const CartComponent = () => {
  const {getUser} = useUserContext();
  const user = getUser();
  const cart = useSelector((state) => state.cart);
  const dispatch = useDispatch();

  const handlePlaceOrder = () => {
    console.log(`place order clicked`);
    cart.map((item)=> {
      console.log(`item.quantity: ${typeof(item.quantity)}`);
      const orderObj = new Order(
        item.itemId ,
        item.restaurantId,
        item.restaurantName,
        user.id,
        user.name,
        item.itemName,
        item.quantity,
        "cooking",
      );
      fetch('http://localhost:8082/api/orders/add', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(orderObj),
        })
            .then((response) => {
                if (response.ok) {
                    alert("Order added successfully!");
                    cart.map((item) => {
                      dispatch(removeFromCart({itemId: item.itemId, restaurantId: item.restaurantId}));
                    });
                } else {
                    alert("Failed to add order.");
                }
            })
            .catch((error) => {
                console.error("Error:", error);
                alert("An error occurred.");
            });
    })

  }

  return (
    <div>
      <h2>🛒 Shopping Cart</h2>
      <button onClick={()=> handlePlaceOrder()}>Place Order</button>
      {cart.length === 0 ? <p>Cart is empty.</p> : (
        <ul>
          {cart.map((item) => (
            <li key={item.itemId}>
              {item.itemName} - ${item.basePrice} x {item.quantity}
              <button onClick={() => dispatch(updateQuantity({ itemId: item.itemId, restaurantId: item.restaurantId, quantity: item.quantity + 1 }))}>➕</button>
              <button onClick={() => dispatch(updateQuantity({ itemId: item.itemId, restaurantId: item.restaurantId, quantity: Math.max(1, item.quantity - 1) }))}>➖</button>
              <button onClick={() => dispatch(removeFromCart({ itemId: item.itemId, restaurantId: item.restaurantId }))}>❌ Remove</button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default CartComponent;

// frontend/frontend-angular/src/app/views/customers/customer-cart/customer-cart.component.ts
import { Component, OnInit } from '@angular/core';
import { CartService, CartItem } from '../../../services/cart.service';
import { CustomerService } from '../../../services/customer.service';
import { UserService } from '../../../services/user.service';
import { Order } from '../../../models/order.model';

@Component({
  selector: 'app-customer-cart',
  imports: [],
  templateUrl: './customer-cart.component.html'
})
export class CustomerCartComponent implements OnInit {
  cart: CartItem[] = [];

  constructor(
    private cartService: CartService,
    private customerService: CustomerService,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    this.cartService.cart$.subscribe((cart) => (this.cart = cart));
  }

  increment(item: CartItem): void {
    this.cartService.updateQuantity(item.itemId, item.restaurantId, item.quantity + 1);
  }

  decrement(item: CartItem): void {
    this.cartService.updateQuantity(item.itemId, item.restaurantId, Math.max(1, item.quantity - 1));
  }

  remove(item: CartItem): void {
    this.cartService.removeFromCart(item.itemId, item.restaurantId);
  }

  handlePlaceOrder(): void {
    const user = this.userService.getUser();
    if (!user) return;

    this.cart.forEach((item) => {
      const orderObj = new Order(
        item.itemId,
        item.restaurantId,
        item.restaurantName,
        user.id,
        user.name,
        item.itemName,
        item.quantity,
        'cooking'
      );
      this.customerService.placeOrder(orderObj).subscribe({
        next: () => {
          alert('Order placed successfully!');
          this.cartService.clearCart();
        },
        error: (err) => {
          console.error('Error placing order:', err);
          alert('Failed to place order.');
        }
      });
    });
  }
}

<div>
  <h2>🛒 Shopping Cart</h2>
  <button (click)="handlePlaceOrder()">Place Order</button>
  @if (cart.length === 0) {
    <p>Cart is empty.</p>
  } @else {
    <ul>
      @for (item of cart; track item.itemId) {
        <li>
          {{ item.itemName }} - ${{ item.basePrice }} x {{ item.quantity }}
          <button (click)="increment(item)">➕</button>
          <button (click)="decrement(item)">➖</button>
          <button (click)="remove(item)">❌ Remove</button>
        </li>
      }
    </ul>
  }
</div>
