// frontend/frontend-angular/src/app/views/auth/delivery-agent-auth/delivery-agent-auth.component.ts
import { Component } from '@angular/core';
import { LoginComponent } from '../login/login.component';
import { SignUpComponent } from '../sign-up/sign-up.component';

@Component({
  selector: 'app-delivery-agent-auth',
  imports: [LoginComponent, SignUpComponent],
  templateUrl: './delivery-agent-auth.component.html'
})
export class DeliveryAgentAuthComponent {
  isLogin: boolean = true;

  toggleAuthMode(): void {
    this.isLogin = !this.isLogin;
  }
}

<div>
  <h1>Delivery Agent Authentication</h1>
  @if (isLogin) {
    <app-login userType="DELIVERYAGENT"></app-login>
  } @else {
    <app-sign-up userType="DELIVERYAGENT"></app-sign-up>
  }
  <button (click)="toggleAuthMode()">
    {{ isLogin ? 'Switch to Signup' : 'Switch to Login' }}
  </button>
</div>

// frontend/food-delivery/src/views/DeliveryAgentAuth.jsx
import React, { useState } from 'react';
import Login from '../components/Auth/Login';
import SignUp from '../components/Auth/SignUp';

function DeliveryAgentAuth() {
  const [isLogin, setIsLogin] = useState(true);

  const toggleAuthMode = () => {
    setIsLogin(!isLogin);
  };

  return (
    <div>
      <h1>Delivery Agent Authentication</h1>
      {isLogin ? (
        <Login userType="DELIVERYAGENT" />
      ) : (
        <SignUp userType="DELIVERYAGENT" />
      )}
      <button onClick={toggleAuthMode}>
        {isLogin ? 'Switch to Signup' : 'Switch to Login'}
      </button>
    </div>
  );
}

export default DeliveryAgentAuth;
