// frontend/frontend-angular/src/app/views/customers/customer-home-screen/customer-home-screen.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { Location } from '@angular/common';

@Component({
  selector: 'app-customer-home-screen',
  templateUrl: './customer-home-screen.component.html',
  styleUrls: ['./customer-home-screen.component.css']
})
export class CustomerHomeScreenComponent implements OnInit {
  userId: string | null = null;
  user: any = {};
  query: string = '';
  results: any[] = [];
  error: string = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private http: HttpClient,
    private location: Location
  ) {}

  ngOnInit(): void {
    this.userId = this.route.snapshot.paramMap.get('userId');

    // Get state data if available
    const navigation = this.router.getCurrentNavigation();
    if (navigation?.extras.state) {
      this.user = navigation.extras.state['user'] || {};
    }
  }

  handleSearch(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      this.error = ''; // Clear previous errors
      const url = `http://localhost:8081/api/customers/search?query=${encodeURIComponent(this.query)}&latitude=26.692284424260034&longitude=88.3774020141318`;

      this.http.get<any[]>(url).subscribe({
        next: (data) => {
          this.results = data;
          console.log('Result received:', data);
        },
        error: (err) => {
          this.error = 'Failed to fetch data';
        }
      });
    }
  }

  handleRestaurantClick(restaurant: any): void {
    console.log('Menu item clicked');
    this.router.navigate(['/restaurantMenu'], { state: { restaurant } });
  }
}

<div>
    <h1>Welcome Customer {{ user?.name || 'User' }}!</h1>
    <p>Your ID: {{ userId }}</p>
  
    <div style="margin-top: 20px;">
      <input
        type="text"
        [(ngModel)]="query"
        (keydown)="handleSearch($event)"
        placeholder="Enter your query and press Enter"
        style="padding: 10px; font-size: 16px; width: 300px; margin-right: 10px;"
      />
    </div>
  
    <p *ngIf="error" style="color: red;">{{ error }}</p>
  
    <ul *ngIf="results.length > 0" style="margin-top: 20px;">
      <li *ngFor="let item of results" (click)="handleRestaurantClick(item)">
        {{ item.restaurantName }}
      </li>
    </ul>
  </div>

// frontend/food-delivery/src/views/customers/CustomerHomeScreen.jsx
import React, { useState } from "react";
import { useParams, useLocation, useNavigate } from "react-router-dom";

const CustomerHomeScreen = () => {
  const navigate = useNavigate();
  const { userId } = useParams(); // Extract the userId from the URL
  const location = useLocation(); // Access additional data passed via state
  const user = location.state?.user;

  // State for the query input and API response
  const [query, setQuery] = useState("");
  const [results, setResults] = useState([]);
  const [error, setError] = useState("");

  // Function to handle the API call
  const handleSearch = async (e) => {
    if (e.key === "Enter") {
      setError(""); // Clear any previous errors
      try {
        const url = `http://localhost:8081/api/customers/search?query=${encodeURIComponent(query)}&latitude=${26.692284424260034}&longitude=${88.3774020141318}`;
        const response = await fetch(url, {
          method: "GET",
        });
        if (!response.ok) {
          throw new Error("Failed to fetch data");
        }
        const data = await response.json();
        setResults(data); // Update results state with the received data
        console.log(`Result received:`, data);
      } catch (err) {
        setError(err.message);
      }
    }
  };

  const handleRestaurantClick = (restaurant) => {
    console.log("menu item clicked");
    navigate(`/restaurantMenu`,{state: {restaurant: restaurant}});
  }

  return (
    <div>
      <h1>Welcome Customer {user?.name || "User"}!</h1>
      <p>Your ID: {userId}</p>

      <div style={{ marginTop: "20px" }}>
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={handleSearch}
          placeholder="Enter your query and press Enter"
          style={{
            padding: "10px",
            fontSize: "16px",
            width: "300px",
            marginRight: "10px",
          }}
        />
      </div>

      {error && <p style={{ color: "red" }}>{error}</p>}

      {results.length > 0 && (
        <ul style={{ marginTop: "20px" }}>
          {results.map((item) => (
            <li key={item.id} onClick ={ () => {handleRestaurantClick(item)}}>{item.restaurantName}</li> 
          ))}
        </ul>
      )}
    </div>
  );
};

export default CustomerHomeScreen;
