// frontend/frontend-angular/src/app/views/customers/restaurant-menu/restaurant-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CustomerService } from '../../../services/customer.service';
import { CartService } from '../../../services/cart.service';

@Component({
  selector: 'app-restaurant-menu',
  imports: [],
  templateUrl: './restaurant-menu.component.html'
})
export class RestaurantMenuComponent implements OnInit {
  restaurant: any = null;
  menus: any[] = [];

  constructor(
    private router: Router,
    private customerService: CustomerService,
    private cartService: CartService
  ) {
    const nav = this.router.getCurrentNavigation();
    this.restaurant = nav?.extras.state?.['restaurant'] || window.history.state?.restaurant || null;
  }

  ngOnInit(): void {
    if (this.restaurant) {
      this.fetchMenus();
    }
  }

  fetchMenus(): void {
    this.customerService.getMenuForRestaurant(this.restaurant.id).subscribe({
      next: (data) => (this.menus = data),
      error: (err) => console.error('Failed to fetch menu:', err)
    });
  }

  handleAddToCart(product: any): void {
    this.cartService.addToCart(product);
  }
}

<div>
  @if (restaurant) {
    <h1>Restaurant menu for: {{ restaurant.restaurantName }}</h1>
    @if (menus.length > 0) {
      <ul>
        @for (menu of menus; track menu.itemId) {
          <li>
            {{ menu.itemName }}
            <button (click)="handleAddToCart(menu)">Add to Cart</button>
          </li>
        }
      </ul>
    }
  } @else {
    <p>No restaurant selected.</p>
  }
</div>

// frontend/food-delivery/src/views/customers/RestaurantMenu.jsx
import { useLocation } from "react-router-dom";
import { useEffect, useState } from "react";
import { useSelector, useDispatch } from 'react-redux';
import {addToCart} from '../../redux/CartSlice';
const RestaurantMenu = () => {

    const location = useLocation();
    const {restaurant} = location.state || {};

    const [menus, setMenus] = useState([]);

    const cart = useSelector((state) => state.cart);
    const dispatch = useDispatch();

    useEffect(() => {
        fetchMenus();
    },[restaurant]);

    const fetchMenus = async () => {
        const response = await fetch(`http://localhost:8081/api/customers/getMenuForRestaurant?restaurantId=${restaurant.id}`, {
            method: "GET",
        });
        if(!response.ok){
            throw new Error("Failed to fetch menu for restaurant");
        }
        const data = await response.json();
        console.log("menus recieved", data);
        setMenus(data);

    }

    const handleAddToCart = (product) => {
        dispatch(addToCart(product));
        console.log(`cart items`);
       
    }
    useEffect(() => {
        console.log("Cart items updated:");
        cart.forEach((item) => console.log("Item:", item));
    }, [cart]);

    return(
        <div>
            <h1>{`restaurant menu for: ${restaurant.restaurantName}`}</h1>
            {menus.length >0 && (
            <ul>{menus.map((menu) => (
                <li>
                    {`${menu.itemName}`}
                    
                    <button onClick={() => {handleAddToCart(menu)}}>Add to Cart</button>
                </li>
            ))}          

            </ul>
            )}
        </div>
    );
};
export default RestaurantMenu;
