// frontend/food-delivery/src/views/CustomerAuth.jsx
import React, { useState } from 'react';
import Login from '../components/Auth/Login';
import SignUp from '../components/Auth/SignUp';

function CustomerAuth() {
  const [isLogin, setIsLogin] = useState(true);

  const toggleAuthMode = () => {
    setIsLogin(!isLogin);
  };

  return (
    <div>
      <h1>Customer Authentication</h1>
      {isLogin ? (
        <Login userType="CUSTOMER" />
      ) : (
        <SignUp userType="CUSTOMER" />
      )}
      <button onClick={toggleAuthMode}>
        {isLogin ? 'Switch to Signup' : 'Switch to Login'}
      </button>
    </div>
  );
}

export default CustomerAuth;

// frontend/frontend-angular/src/app/views/auth/customer-auth/customer-auth.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-customer-auth',
  templateUrl: './customer-auth.component.html',
  styleUrls: ['./customer-auth.component.css']
})
export class CustomerAuthComponent {
  isLogin: boolean = true;

  toggleAuthMode(): void {
    this.isLogin = !this.isLogin;
  }
}

<div>
    <h1>Customer Authentication</h1>
    <app-login *ngIf="isLogin" userType="CUSTOMER"></app-login>
    <app-sign-up *ngIf="!isLogin" userType="CUSTOMER"></app-sign-up>
    <button (click)="toggleAuthMode()">
      {{ isLogin ? 'Switch to Signup' : 'Switch to Login' }}
    </button>
  </div>
