// frontend/frontend-angular/src/app/views/auth/sign-up/sign-up.component.ts
import { Component, Input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../services/api.service';

@Component({
  selector: 'app-sign-up',
  imports: [FormsModule],
  templateUrl: './sign-up.component.html'
})
export class SignUpComponent {
  @Input() userType: string = '';
  formData = { name: '', email: '', password: '', phone: '' };

  constructor(private apiService: ApiService) {}

  handleSubmit(): void {
    this.apiService.signup(this.userType, this.formData).subscribe({
      next: (user) => alert(`Signup successful for user: ${user.name}`),
      error: (err) =>
        alert(`Signup failed: ${err.error?.message || err.message}`)
    });
  }
}

<form (ngSubmit)="handleSubmit()">
  <h2>{{ userType }} Signup</h2>
  <div>
    <label>Name</label>
    <input type="text" name="name" placeholder="Enter your name" [(ngModel)]="formData.name" required />
  </div>
  <div>
    <label>Email</label>
    <input type="email" name="email" placeholder="Enter your email" [(ngModel)]="formData.email" required />
  </div>
  <div>
    <label>Password</label>
    <input type="password" name="password" placeholder="Enter your password" [(ngModel)]="formData.password" required />
  </div>
  <div>
    <label>Phone</label>
    <input type="tel" name="phone" placeholder="Enter your phone number" [(ngModel)]="formData.phone" />
  </div>
  <button type="submit">Sign Up</button>
</form>

// frontend/food-delivery/src/components/Auth/SignUp.jsx
import React, { useState } from 'react';
import { signup } from '../../services/apiServices';

function SignUp({ userType }) {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    phone: ''
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await signup(userType, formData);
      const user = response.data;
      alert(`Signup Successfull for user : ${user.name}`);
    } catch (error) {
      alert("Signup failed: " + error.response?.data?.message || error.message);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <h2>{userType} Signup</h2>
      
      <div>
        <label>Name</label>
        <input
          type="text"
          name="name"
          placeholder="Enter your name"
          value={formData.name}
          onChange={handleChange}
          required
        />
      </div>
      
      <div>
        <label>Email</label>
        <input
          type="email"
          name="email"
          placeholder="Enter your email"
          value={formData.email}
          onChange={handleChange}
          required
        />
      </div>
      
      <div>
        <label>Password</label>
        <input
          type="password"
          name="password"
          placeholder="Enter your password"
          value={formData.password}
          onChange={handleChange}
          required
        />
      </div>
      
      <div>
        <label>Phone</label>
        <input
          type="tel"
          name="phone"
          placeholder="Enter your phone number"
          value={formData.phone}
          onChange={handleChange}
        />
      </div>
      
      <button type="submit">Sign Up</button>
    </form>
  );
}

export default SignUp;
