// frontend/food-delivery/src/views/customers/CustomerOrders.jsx


import { useEffect, useState } from "react";
import { useUserContext } from "../../contexts/UserProvider";
import CustomerController from "../../controllers/CustomerController";

const CustomerOrders = () => {
    const {getUser} = useUserContext();
    const user = getUser();
    const [orders, setOrders] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchOrders = async () => {
            try {
                const orderList = await CustomerController.getOrdersByUserId(user);
                setOrders(orderList);
            } catch (err) {
                setError("Failed to fetch orders");
            } finally {
                setLoading(false);
            }
        };

        fetchOrders();
    }, [user]);

    if (loading) return <p>Loading orders...</p>;
    if (error) return <p>{error}</p>;

    return (
        <div>
            <h1>Orders</h1>
            <table border="1">
                <thead>
                    <tr>
                        <th>Item Name</th>
                        <th>Restaurant</th>
                        <th>Quantity</th>
                        <th>Date & Time</th>
                    </tr>
                </thead>
                <tbody>
                    {orders.length > 0 ? (
                        orders.map((order, index) => (
                            <tr key={index}>
                                <td>{order.itemName}</td>
                                <td>{order.restaurantName}</td>
                                <td>{order.quantity}</td>
                                <td>{order.createdAt}</td>
                            </tr>
                        ))
                    ) : (
                        <tr>
                            <td colSpan="4">No orders found</td>
                        </tr>
                    )}
                </tbody>
            </table>
        </div>
    );
};

export default CustomerOrders;

// frontend/frontend-angular/src/app/views/customers/customer-orders/customer-orders.component.ts
import { Component, OnInit } from '@angular/core';
import { CustomerService } from '../../../services/customer.service';
import { UserService } from '../../../services/user.service';
import { Order } from '../../../models/order.model';

@Component({
  selector: 'app-customer-orders',
  imports: [],
  templateUrl: './customer-orders.component.html'
})
export class CustomerOrdersComponent implements OnInit {
  orders: Order[] = [];
  loading: boolean = true;
  error: string = '';

  constructor(
    private customerService: CustomerService,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    const user = this.userService.getUser();
    if (!user) {
      this.error = 'User not found.';
      this.loading = false;
      return;
    }
    this.customerService.getOrdersByUserId(user.id).subscribe({
      next: (orders) => {
        this.orders = orders;
        this.loading = false;
      },
      error: () => {
        this.error = 'Failed to fetch orders.';
        this.loading = false;
      }
    });
  }
}

<div>
  @if (loading) {
    <p>Loading orders...</p>
  } @else if (error) {
    <p>{{ error }}</p>
  } @else {
    <h1>Orders</h1>
    <table border="1">
      <thead>
        <tr>
          <th>Item Name</th>
          <th>Restaurant</th>
          <th>Quantity</th>
          <th>Date & Time</th>
        </tr>
      </thead>
      <tbody>
        @if (orders.length > 0) {
          @for (order of orders; track $index) {
            <tr>
              <td>{{ order.itemName }}</td>
              <td>{{ order.restaurantName }}</td>
              <td>{{ order.quantity }}</td>
              <td>{{ order.createdAt }}</td>
            </tr>
          }
        } @else {
          <tr><td colspan="4">No orders found</td></tr>
        }
      </tbody>
    </table>
  }
</div>
